abstract class CalculateChargingStates {}

class CalculateChargingInitState extends CalculateChargingStates {}

class SelectChoiceSuccessCalculateState extends CalculateChargingStates {}

class YesOrNoChangedSuccessCalculateState extends CalculateChargingStates {}

class PerformToggleSuccessCalculateState extends CalculateChargingStates {}
class ToggleScreensSuccessCalculateState extends CalculateChargingStates {}
class PerformToggleMenuSuccessCalculateState extends CalculateChargingStates {}
class PerformSwitchFawrySuccessCalculateState extends CalculateChargingStates {}
class PerformSwitchVodCashSuccessCalculateState extends CalculateChargingStates {}
class PerformSwitchVisaSuccessCalculateState extends CalculateChargingStates {}
class PerformSwitchMandoobSuccessCalculateState extends CalculateChargingStates {}
class PerformSwitchCashSuccessCalculateState extends CalculateChargingStates {}
