import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData wallet = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weight = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsapp = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData width = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData agenda = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bomb2 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_income = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash_back = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData categories = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData company = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData confirm = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact_us_2 = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crying = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delivery_truck = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drop = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_2 = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email1 = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData factory_icon = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fashion = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feedback = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feedbackkk = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData furnitures = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_browser = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_glass_logo = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData happy = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData happy1 = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData happynew = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData happynew1 = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData headphones = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData login = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loudspeaker = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loupe = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medicine = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_accounting_4679331 = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_app_2465542 = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_application_1603837 = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_cash_on_delivery_3881853 = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_complaint_2048408 = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_complaints_3385052 = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_customer_demand_3437164 = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_inventory_3377901 = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_next_1442934 = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_notification_4625948 = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_offer_1055801 = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_phone_4668781 = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_pick_up_4160044 = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_preloader_1773263 = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_shipping_3484992 = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_sms_1953496 = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_success_4213622 = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_talk_4679128 = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_time_1015010 = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_trash_2908521 = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData office_building = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData online_shopping_new = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order_confirmation = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData package = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData padlock = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData party = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pet = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData placeholder = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plug = IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData promotion = IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rating = IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resturant = IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sad = IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sad1 = IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sadnew = IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sadnew1 = IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_3_ = IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_1 = IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store = IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData surprised = IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData surprised1 = IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telephone = IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telephone1 = IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track = IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trafficSignal = IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tray = IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trueIcon = IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_support = IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verified_list_of_exercises_of_a_gymnast_on_a_clipboard = IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verify = IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
class ShipIcon {
  ShipIcon._();

  static const _kFontFam = 'ShipIcon';
  static const String? _kFontPkg = null;

  static const IconData myshipping = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}